[tools]
'asdf:asdf-community/asdf-direnv' = 'latest'
'asdf:asdf-community/asdf-uv' = 'latest'
'asdf:luizm/asdf-shellcheck' = 'latest'
'asdf:luizm/asdf-shfmt' = 'latest'
'asdf:mise-plugins/mise-pipx' = 'latest'
'asdf:mise-plugins/mise-usage' = 'latest'
'asdf:salasrod/asdf-mkcert' = 'latest'

'go:github.com/DarthSim/hivemind' = 'latest'

'pipx:doge' = 'latest'
'pipx:internetarchive' = 'latest'
'pipx:proselint' = 'latest'
'pipx:visidata' = 'latest'
'pipx:sqlit-tui' = 'latest'

'ubi:BurntSushi/xsv' = 'latest'
'ubi:anordal/shellharden' = 'latest'
'ubi:cloverstd/tcping' = 'latest'
'ubi:direnv/direnv' = 'latest'
'ubi:jqlang/jq' = 'latest'
'ubi:mikefarah/yq' = 'latest'
'ubi:sclevine/yj' = 'latest'
'ubi:tomnomnom/gron' = 'latest'

rust = 'latest'

go = 'latest'
node = 'latest'
# pnpm = '10'
python = 'latest'

[settings]
activate_aggressive = true
always_keep_download = false
always_keep_install = false
asdf_compat = false
disable_hints = ['python_multi']
env_file = '.env'
experimental = true
go_set_gopath = false
go_set_goroot = false
go_skip_checksum = true
idiomatic_version_file_enable_tools = ["node", "python", "ruby"]
legacy_version_file = true
not_found_auto_install = true
paranoid = false
plugin_autoupdate_last_check_duration = '1 week'
raw = false
task_output = 'prefix'
trusted_config_paths = ['~/code', '~/src']
verbose = false
yes = false

[settings.python]
default_packages_file = "~/.default-python-packages"

[settings.ruby]
default_packages_file = "~/.default-ruby-packages"
